### ISSUE TITLE
Can we add or start using a standard icon/logo for each tool under ACS Commons?

### ISSUE THREAD

**Issue by ksurendra** [Adobe-Consulting-Services/adobe-consulting-services.github.io#121]
We have about 60 tools under ACS Commons as of v3.16.0 and obviously each tool has it's own logo. 

![acs-commons-all-tools-v3 16 0](https://user-images.githubusercontent.com/902972/40343940-003d3318-5d58-11e8-89c6-9e2bf3f681c8.png)

These are great working tools, no offense to the creator, but looking at them, some of them do not appear **Professional**. I understand this being an open-source project we cannot enforce a rule but maybe some guidelines, if we can?

Can we start using or creating a standard logo for each tool existing and new ones that will be created? I've created some samples (as below). We need not use these, adding them to elaborate my point. 

![on-deploy-scripts](https://user-images.githubusercontent.com/902972/40344039-89d3e658-5d58-11e8-8e6b-bc5e3f1ebe6f.png)

![report-builder](https://user-images.githubusercontent.com/902972/40344040-89e3f2e6-5d58-11e8-82a5-6a91e942abc7.png)

![ensureauthroizable](https://user-images.githubusercontent.com/902972/40344041-89f95294-5d58-11e8-9038-35a0e6c8dde4.png)

![utils-and-apis](https://user-images.githubusercontent.com/902972/40344042-8a087d0a-5d58-11e8-8288-e73ed6c0d66f.png)

**Comment by davidjgonzalez** [comment]
@ksurendra we wouldn't need the ACS Commons logo/blurb at the bottom since this is on the ACS Commons web site.

The downside of this approach is we'd have 60 "items" (cards, list, however they'd manifest) that look identical without visual cues that indicate what the feature is "about" (ex. Social Integrations card has Twitter and Linked In, i can glance at the card and get a pretty good idea without reading the text)

Do you have suggestions on a more professional, while maintaining a visual cue per feature?

Also, do we know this is a problem? Are ppl not avoiding Commons because of this? Conversely, has Commons enjoyed rapid adoption because it's not your run of the mill, super-dry, enterprise software web site? (IDK the answer to either of these)

**Comment by badvision** [comment]
I like my MCP logo.  I would neither want to change it to something more drab, nor would I expect others to use a blue glowing Bauhaus font for their stuff.  Likewise, I have no plans to remove some of the new fun logos I put on the MCP Tools page.  Totally would love to see some suggestions for features which have no icon today, but it's supposed to look like a grab bag of party favors and toys you want to play with.  That's part of the charm.

**Comment by ksurendra** [comment]
I'm convinced @davidjgonzalez and @badvision  . It was just a different eye or a way of looking at them.
