### ISSUE TITLE
Not able to save cq:name property to jcr:content node using mcp tool URL importer

### ISSUE THREAD

**Issue by praveenv2018** [Adobe-Consulting-Services/adobe-consulting-services.github.io#177]
I am using MCP tool URL importer to upload assets and assign metadata. Metadata is saving to metadata node but the property cq:name is not saving to jcr:content node. I am using the excel header for this property as ../../jcr:content/cq:name. Can you please guide me how to achieve this?

**Comment by badvision** [comment]
I'm pretty sure that cq:name is not a physical property and is actually the same as the node name as found in the node path.  cq:name is provided for queries so that your query can use statements relevant to the naming of a given node, or so that when looking at results you can refer to the name of the node without having to split it off the path.  I've never known cq:name to be a modifiable property.  If you change the path which you are saving to, does that not already set the cq:name virtual property to the same value?
