### ISSUE TITLE
Documentation for ACS AEM Commons Touch UI Multifield Extension

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/adobe-consulting-services.github.io#47]
Documentation for https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/437

**Comment by davidjgonzalez** [comment]
@schoudry  @justinedelson  - is this different than the GraniteUI multifield [1] other than the serialization methods (JSON or composite; where as the OOTB is a composite structure)

I take it this isnt documented? which seems strange since this has 3 open bugs? (how are they even finding out about this!! surely not looking through issues and PRs?!!)

https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/reference-materials/granite-ui/api/jcr_root/libs/granite/ui/components/coral/foundation/form/multifield/index.html

**Comment by justinedelson** [comment]
There's actually documentation in the JS file(s). To your question, it is different than the GraniteUI multifield in that it works on 6.2 :) Unless there's some compelling reason not to, I think we should deprecate it. Sooner or later, we're going to drop 6.2 support anyway at which point there will be no reason to use this (again, unless I'm missing some compelling feature).

**Comment by davidjgonzalez** [comment]
@justinedelson was just coming back to ask if its ok to deprecate it :)

For now, ive create a shell page (that links to HS2's write up) under UI Widgets and marked as deprecated. The feature page for it also has a banner suggesting folks try out the GraniteUI option (though i might drop a note in it stating that only works on 6.3+) 

Closing this since i dont think we want to spend more time documenting this since its deprecated and H2S did a good job on their blog.
